#!/bin/bash
# Backup files in stm8ef and replace them by sym links.

stm8ef_path=$(readlink -f stm8ef)
muforth_path=$(readlink -f muforth)
here=$(pwd)

rename=(
 inc/defconf.inc
 inc/sser.inc
 inc/sser_fdx.inc
 inc/bgtask.inc
 forth.asm
)
for i in "${rename[@]}"
do mv "$stm8ef_path"/"$i" "$stm8ef_path"/"$i"_original
done

for i in stm8ef_mu/muforth_inc/*;
do ln -s "$here"/"$i" "$stm8ef_path"/inc/"${i#stm8ef_mu/muforth_inc/}"
done

ln -s "$here"/stm8ef_mu/forth.asm "$stm8ef_path"/forth.asm
ln -s "$here"/mu/target/STM8 "$muforth_path"/mu/target
ln -s "$here"/mu/tools/ "$muforth_path"/mu
ln -s "$here"/mu/work "$muforth_path"/mu

targ=(
 MINDEV
 W1209-FD
 STM8L051F3
)
for i in "${targ[@]}"
do cp "$stm8ef_path"/"$i/target.inc" "$stm8ef_path"/"$i/target.inc"_original
sed -i '/UPPLOC/i\.ifeq MUFORTH' "$stm8ef_path"/"$i/target.inc"
sed -i '/UPPLOC/a\.endif'        "$stm8ef_path"/"$i/target.inc"

cp "$stm8ef_path"/"$i/globconf.inc" "$stm8ef_path"/"$i/globconf.inc"_original
sed -i '/; Clock:/a\\n        MUFORTH          = 1    ; No compiler nor interpreter' "$stm8ef_path"/"$i/globconf.inc"

cp "$stm8ef_path"/"$i/boardcore.inc" "$stm8ef_path"/"$i/boardcore.inc"_original
sed -i '/;       Put c to board outputs,/a\\n.if MUFORTH\n        HEADER  OUTSTOR "OUT!"\n.else' "$stm8ef_path"/"$i/boardcore.inc"
sed -i '/        .ascii  "OUT!"/a\.endif' "$stm8ef_path"/"$i/boardcore.inc"

done