#!/bin/bash
# This script is called from muforth to edit the output of "naken_util -disasm -STM8"
#  to reflect the addresses of equates and words of the target.

# concatinate "target.con", "target" and "target-runtime" to "xtokens"
cat /tmp/target.con /tmp/target /tmp/target-runtime >/tmp/xtokens.txt

# remove space after ","
sed -i 's/, /,/' /tmp/out.txt

# replace adresses with names
awk --non-decimal-data '
BEGIN {Argind=0; ;empty_file=0;printf("\n\n");getline nextline < "/tmp/out.txt"}

# Check for empty file. If there are no ?branch instructions nop.txt is empty
ARGIND > Argind + 1 {
    for (Argind++; Argind < ARGIND; Argind++)
        zerofile(ARGV[Argind], Argind) }
ARGIND != Argind { Argind = ARGIND }

# process /tmp/xtokens.txt
# fill array with (addres,names) from /tmp/xtokens.txt
FNR==NR { A[tolower($1)]=$2 ; if ($1~/^\$0./) A[gensub(/0*/,"",1,tolower($1))]=$2 ;iA ++ ;next}

# process /tmp/nop.txt
# fill array B with addresses of branch instructions and respective branch addresses
NR==FNR+iA && empty_file==0 { B[$1]=$2;print $1,B[$1];  next}

# process /tmp/out.txt
# addr2: get the addres of the next line, index of getline is incremented in BEGIN section:
{ getline nextline < "/tmp/out.txt" ;split(nextline,a);addr2=a[1]}

# skip header of naken_util
FNR<14 {next}

# addr0 is start address
FNR==14 { addr0 = $1}

# skip 1 instruction to display branch addresses properly
skip==-1 { skip=0;next}

calc()

# strip "0x0" and ":" in out.txt
{addr=$1;qq=gensub(/0x0*/,"$",1,$1);addr1=gensub(/:/,"",1,qq)}

{cy=$NF; $NF="" }
{for (i=3;i<NF;i++) {
     if ($i in A) $i=A[$i]
     if (gensub(/,.*$/,"",1,$i) in A) $i=A[gensub(/,.*$/,"",1,$i)]gensub(/^.{1,5}/,"",1,$i)
     if (gensub(/^.*,/,"",1,$i) in A) $i=gensub(/,.*$/,"",1,$i)","A[gensub(/^.*,/,"",1,$i)] }}

# start of word: print word name
addr1 in A {print A[addr1]}

# ?branch instructions
addr1 in B {cell=B[addr1]; cy=0; $2=gensub(/..$/,"\\1",1,cell); $3=gensub(/^../,"\\1",1,cell);$0=$1" "$2" "$3" branch addr: $"cell" "cy; skip=-1;}

$6~/^[a-f0-9]{2}$/ {
        printf("$%x\t%s %s %s %s %s ",$1,$2,$3,$4,$5,$6);$1=$2=$3=$4=$5=$6="";
        printf("%40s%5s\n", $0,cy);cycles();add=5;next}
$5~/^[a-f0-9]{2}$/ {
        printf("$%x\t%s %s %s %s ",$1,$2,$3,$4,$5);$1=$2=$3=$4=$5="";
        printf("%43s%5s\n", $0,cy);cycles();add=4;next}
$4~/^[a-f0-9]{2}$/ {
        printf("$%x\t%s %s %s ",$1,$2,$3,$4);$1=$2=$3=$4="";
        printf("%46s%5s\n", $0,cy);cycles();add=3;next}
$3~/^[a-f0-9]{2}$/ {
        printf("$%x\t%s %s ",$1,$2,$3);$1=$2=$3="";
        printf("%49s%5s\n", $0,cy);cycles();add=2;next}
$3!~/^[a-f0-9]{2}$/ {
        printf("$%x\t%s ",$1,$2);$1=$2="";
        printf("%52s%5s\n", $0,cy);cycles();add=1}

# print byte count and cycle count
END {if (difcy>0) {
        printf( "%4d bytes%58d-%2d cycles\n", addr+add-addr0,mincy,mincy+difcy);}
        else { printf( "%4d bytes%58d cycles\n", addr+add-addr0,mincy)}
}
# count cycles total
function cycles() {
        mincy+=substr(cy,1);
        if (cy ~/-/) {
                difcy+=substr(cy,3,2)-substr(cy,1);
        }
}
# find the "offset" column
function find_col() {
        for (i=3; i<NF; i++) {
                if ($i~/offset/) {
                        return i;
                }
        }
}
# correct the addresses of jumps and calls 
function calc() {
        if ($0~/offset/) {
                i=find_col()
                pos=index($0,"offset");
                len=length($i) - 9;
                OFFSET=substr($0,pos+7,len);
                addr3=sprintf("$%x",addr2+OFFSET);
                if (addr3 in A)  addr3=A[addr3];
                $(i-1)=addr3;
        }
}
function zerofile(i,j) {
        empty_file=-1 ;
}
        
'  /tmp/xtokens.txt /tmp/nop.txt /tmp/out.txt 
